# Details: https://github.com/kirill-markin/repo-to-text
# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and "Contents of ..." sections
ignore-tree-and-content:
  - "db"
  - "bundle_cache"
  - ".repo-to-text-settings.yaml"
  - "api/data"
  - "front/node_modules"
  - "front/.pnpm-store"
  - "front/.svelte-kit"
  - "front/build"
  - ".env*"
  - "front/src/lib/components/ui"
  - "front/static"

# Ignore files and directories for "Contents of ..." section
ignore-content:
  - "README.md"
  - "LICENSE"
