services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "bundle config set frozen true && bundle install && bundle exec rerun --background --force-polling -- rackup -o 0.0.0.0 -p 9292",
      ]
    volumes:
      - ./api:/app
      - bundle_cache:/var/bundle_cache
    environment:
      - BUNDLE_PATH=/var/bundle_cache
      - DB_HOST=finascope-mysql
      - DB_PORT=3306
      - DB_USER=finascope_app
      - DB_PASSWORD=finascope_app_password
      - DB_NAME=finascope
    networks:
      - finascope-net
  openapi:
    # access the OpenAPI documentation at http://localhost:8081
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/openapi_swagger_doc.json:/docs/swagger.json
    environment:
      - SWAGGER_JSON=/docs/swagger.json
    ports:
      - "8081:8080"

volumes:
  bundle_cache:

networks:
  finascope-net:
    external: true
    name: finascope-net
