services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "bundle config set frozen true && bundle install && bundle exec rackup -o 0.0.0.0 -p 9292",
      ]
    volumes:
      - ./api:/app
      - ./db:/var/finascope/db
      - ./bundle_cache:/var/bundle_cache
    environment:
      - FS_SQLITE_FILE=/var/finascope/db/finascope.sqlite3
      - BUNDLE_PATH=/var/bundle_cache
    ports:
      - "9292:9292"
