services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "bundle config set frozen true && bundle install && bundle exec rackup -o 0.0.0.0 -p 9292",
      ]
    volumes:
      - ./api:/app
      - bundle_cache:/var/bundle_cache
    environment:
      - BUNDLE_PATH=/var/bundle_cache
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=finascope_app
      - DB_PASSWORD=finascope_app_password
      - DB_NAME=finascope
    ports:
      - "9292:9292"

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
    user: 1000:1000
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d

volumes:
  bundle_cache:
