services:
  mysql:
    container_name: finascope-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
    user: 1000:1000
    volumes:
      - finascope_mysql_data:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - finascope-net

networks:
  finascope-net:
    name: finascope-net

volumes:
  finascope_mysql_data: