# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "grape", "~> 2.4"

gem "rack", "~> 3.1"
gem "rackup", "~> 2.2"

gem "puma", "~> 6.6"

gem "nanoid", "~> 2.0"

gem "activerecord", "~> 8.0"

gem "sqlite3", "~> 2.6"

gem "rerun", "~> 0.14.0"

gem "kaminari", "~> 1.2"

gem "grape-entity", "~> 1.0"

gem "jwt", "~> 2.10"

gem "mysql2", "~> 0.5.6"

gem "grape-swagger", "~> 2.1"

gem "grape-swagger-entity", "~> 0.7.0"

gem "rake"

group :test do
  gem "rspec", "~> 3.13"
  gem "database_cleaner-active_record", "~> 2.2"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
end
